export enum CarColor {
  WHITE = 'white',
  BLACK = 'black',
  SILVER = 'silver',
  GRAY = 'gray',
  BLUE = 'blue',
  RED = 'red',
  GREEN = 'green',
  BROWN = 'brown',
  YELLOW = 'yellow',
  ORANGE = 'orange',
  PURPLE = 'purple',
  GOLD = 'gold',
  OTHER = 'other',
}
