export enum CarBodyType {
  SEDAN = 'sedan',
  HATCHBACK = 'hatchback',
  SUV = 'suv',
  COUPE = 'coupe',
  CONVERTIBLE = 'convertible',
  WAGON = 'wagon',
  VAN = 'van',
  MINIVAN = 'minivan',
  PICKUP = 'pickup',
  CROSSOVER = 'crossover',
  ROADSTER = 'roadster',
  JEEP = 'jeep',
  LIFTBACK = 'liftback',
  FASTBACK = 'fastback',
  MICRO = 'micro',
  CABRIOLET = 'cabriolet',
  TARGA = 'targa',
  TRUCK = 'truck',
  BUS = 'bus',
  OTHER = 'other',
}
