export enum CarBodyType {
  SEDAN = 'Sedan',
  HATCHBACK = 'Hatchback',
  SUV = 'SUV',
  COUPE = 'Coupe',
  CONVERTIBLE = 'Convertible',
  WAGON = 'Wagon',
  VAN = 'Van',
  MINIVAN = 'Minivan',
  PICKUP = 'Pickup',
  CROSSOVER = 'Crossover',
  ROADSTER = 'Roadster',
  JEEP = 'Jeep',
  LIFTBACK = 'Liftback',
  FASTBACK = 'Fastback',
  MICRO = 'Micro',
  CABRIOLET = 'Cabriolet',
  TARGA = 'Targa',
  TRUCK = 'Truck',
  BUS = 'Bus',
  OTHER = 'Other',
}
